<!-- include css files -->
<?php echo $this->tag->stylesheetLink("css/datepicker.min.css");?>
<?php echo $this->tag->stylesheetLink("css/font-awesome.min.css");?>
<?php echo $this->tag->stylesheetLink("css/bootstrap.min.css");?>
<?php echo $this->tag->stylesheetLink("css/mystyle.css");?>
<?php echo $this->tag->stylesheetLink("css/responsive.css");?>
<!-- include js files -->
<?php echo $this->tag->javascriptInclude("js/jquery-1.12.3.min.js");?>
<?php echo $this->tag->javascriptInclude("js/bootstrap.min.js");?>
<?php echo $this->tag->javascriptInclude("js/myplugin.js");?>
<?php echo $this->tag->javascriptInclude("js/datepicker.min.js");?>


<h2 class="text-center h1">Add new Trainer</h2>

<?php echo $this->tag->form('index/add') ?>
    <div class="container">
        <div class="row">
            <div class="form-group  col-sm-4">
                <label for="name">Name</label>
                <?php echo $form->render('name',["class"=> "form-control"]); ?>
            </div>

            <div class="form-group  col-sm-4">
                    <label for="name">E-Mail</label>
                    <?php echo $form->render("email",["class"=>"form-control"]) ?>
            </div>
            <div class="form-group  col-sm-4">
                <label for="phone">Phone</label>
                <?php echo $form->render("phone",["class"=>"form-control"]) ?>
            </div>
        </div>
        <div class="row">
            <div class="form-group  col-sm-4">
                <label for="initial_interview_date">initial Interview Date</label>
                 <?php echo $form->render("initial_interview_date",["class"=>"datepicker form-control"]) ?>
            </div>
            <div class="form-group  col-sm-4">
                <label for="start_date_trial_period">Start Date Trial Period</label>
                 <?php echo $form->render("start_date_trial_period",["class"=>"datepicker form-control"]) ?>
            </div>
            <div class="form-group col-sm-4">
                <label for="end_date_trial_period">End Date Trial Period</label>
                 <?php echo $form->render("end_date_trial_period",["class"=>"datepicker form-control"]) ?>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-4">
                <label for="spec_id">Specialization</label>
                <?php echo $form->render("spec_id",["class"=>"form-control"]) ?>
            </div>
            <div class="form-group col-sm-4">
                <label for="initial_assessment">initial assessment</label>
                <?php echo $form->render("initial_assessment",["class"=>"form-control"]) ?>
            </div>

            <div class="form-group col-sm-4">
                <label for="end_trial_period_assessment">end Trial Period Assessment</label>
                <?php echo $form->render("end_trial_period_assessment",["class"=>"form-control"]) ?>
            </div>
        </div>
        <div class="row">

            <div class="form-group col-sm-4">
                <label for="cv">cv</label>
                <?php echo $form->render("cv",["class"=>"form-control"]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <?php echo $this->tag->submitButton(["Register","class"=>"btn btn-primary"]) ?>
            
                <?php echo $this->tag->linkTo(["index/browse", "browse All trainers","class"=>"btn btn-primary"]); ?>
                
                <?php echo $this->tag->linkTo(["Specilization", "Add speclization","class"=>"btn btn-primary"]); ?>
            </div>
        </div>
    </div>
</form>
