<!-- include css files -->
<?php echo $this->tag->stylesheetLink("css/datepicker.min.css");?>
<?php echo $this->tag->stylesheetLink("css/font-awesome.min.css");?>
<?php echo $this->tag->stylesheetLink("css/bootstrap.min.css");?>
<?php echo $this->tag->stylesheetLink("css/mystyle.css");?>
<?php echo $this->tag->stylesheetLink("css/responsive.css");?>
<!-- include js files -->
<?php echo $this->tag->javascriptInclude("js/jquery-1.12.3.min.js");?>
<?php echo $this->tag->javascriptInclude("js/bootstrap.min.js");?>
<?php echo $this->tag->javascriptInclude("js/myplugin.js");?>
<?php echo $this->tag->javascriptInclude("js/datepicker.min.js");?>


<h2 class="text-center h1">Login</h2>

<?php echo $this->tag->form('User/login') ?>
    <div class="container">
        <div class="row">
            <div class="form-group col-sm-offset-4 col-sm-4">
                <label for="username">Username</label>
                <?php echo $form->render('username',["class"=> "form-control"]); ?>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-offset-4 col-sm-4">
                <label for="email">Email</label>
                <?php echo $form->render('email',["type"=>"email","class"=> "form-control"]); ?>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-offset-4 col-sm-4">
                <label for="password">Password</label>
                <?php echo $form->render('password',["class"=> "form-control"]); ?>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-offset-4 col-sm-4">
                <?php echo $this->tag->submitButton(["login","class"=>"btn btn-primary"]) ?>
            </div>
        </div>
    </div>
</form>
